### ISSUE TITLE
Wrong authorization method in WebChatApi

### ISSUE THREAD

**Issue by L-L-the-noob** [MyPureCloud/platform-client-sdk-javascript#3]
I was working with WebChatApi and I noticed that the programme failed on sending message for client with a wrong header. So I debug it and traced into my codes which turns out it's not my codes but this module's logic error.

In your `/dist/node/purecloud-platform-client-v2.js` , the following apis put wrong parameter to `callApi()` :

	postWebchatGuestConversationMemberMessages(conversationId, memberId, body) { 
		// skipped

		return this.apiClient.callApi(
			'/api/v2/webchat/guest/conversations/{conversationId}/members/{memberId}/messages', 
			'POST', 
			{ 'conversationId': conversationId,'memberId': memberId }, 
			{  }, 
			{  }, 
			{  }, 
			body, 
			['PureCloud OAuth'], 
			['application/json'], 
			['application/json']
		);
	}

Also this:

	deleteWebchatGuestConversationMember(conversationId, memberId) { 
		// skipped

		return this.apiClient.callApi(
			'/api/v2/webchat/guest/conversations/{conversationId}/members/{memberId}', 
			'DELETE', 
			{ 'conversationId': conversationId,'memberId': memberId }, 
			{  }, 
			{  }, 
			{  }, 
			null, 
			['PureCloud OAuth'], 
			['application/json'], 
			['application/json']
		);
	}

And this:

	postWebchatGuestConversationMemberTyping(conversationId, memberId) { 
		// skipped

		return this.apiClient.callApi(
			'/api/v2/webchat/guest/conversations/{conversationId}/members/{memberId}/typing', 
			'POST', 
			{ 'conversationId': conversationId,'memberId': memberId }, 
			{  }, 
			{  }, 
			{  }, 
			null, 
			['PureCloud OAuth'], 
			['application/json'], 
			['application/json']
		);
	}

Notice that all the apis are using `['PureCloudOAuth']` ? They should use `['Guest Chat JWT']` instead. When I modified the code and rerun my programme, I got the message sent to agent. Perhaps you guys could fix this in the next version of release.

And BTW, I also found a slightly off topic issue (cause I don't know where should I report it).
In [this](https://developer.mypurecloud.com/api/rest/client-libraries/javascript/WebChatApi.html#postWebchatGuestConversationMemberMessages) documentation, notice the example:

	let Guest Chat JWT = platformClient.ApiClient.instance.authentications['Guest Chat JWT'];
	Guest Chat JWT.apiKey = 'YOUR API KEY';

I afraid that's not how javascript syntax works. I think you mean to name it `Guess_Chat_JWT`.

**Comment by PrinceNebulon** [comment]
If you're using the guest chat APIs, please use the guest chat SDK. https://developer.mypurecloud.com/api/rest/client-libraries/javascript-guest/index.html
