### ISSUE TITLE
[question] changelog

### ISSUE THREAD

**Issue by Loyc59** [MyPureCloud/platform-client-sdk-javascript#4]
Hello,

Do you have a centralized changelog ?

I am currently on v68.0.0 and it is hard to sum up all the changes (breaking/major/minor) until the current one.

Best

**Comment by PrinceNebulon** [comment]
The process to get that is a few steps, but yes. 

1. Determine the old Platform version, which is 3704 for SDK v68.0.0. This is determined by viewing the release notes for the specific version. I.e. https://github.com/MyPureCloud/platform-client-sdk-javascript/blob/1252cb1398977e716299d8c0c0fb257fabcfb023/releaseNotes.md
2. Determine the new Platform version using the same method above, or just assume the biggest number is latest.
3. Visit the [Versioning](https://developer.mypurecloud.com/api/rest/versioning.html) page on the dev center and do a diff from the old to the new version with the _Use SDK versioning rules_ option checked. To diff v68.0.0 against the latest, that would be API versions 3704 to 4112 (as of this comment).
