### ISSUE TITLE
Oauth implicit redirect url is wrong

### ISSUE THREAD

**Issue by kevinclarkadstech** [MyPureCloud/platform-client-sdk-javascript#5]
const client = platformClient.ApiClient.instance;
client.loginClientCredentialsGrant(clientId,clientSecret)

Hi, this method redirects to: http://login.purecloud.com/, but I need it to redirect to https://login.usw2.pure.cloud because my organization is in the West region.  How to go about this?

**Comment by baksten** [comment]
Hi,

if you want to connect to a Genesys Cloud environment other than mypurecloud.com, you need to set the environment on the `ApiClient` instance with the PureCloudRegionHosts object.

This can be done with the following line:
`client.setEnvironment(platformClient.PureCloudRegionHosts.us_west_2);`

The region names with their corresponding url can be found in [this](https://github.com/MyPureCloud/platform-client-sdk-javascript/blob/master/build/src/purecloud-platform-client-v2/PureCloudRegionHosts.js) source file.


Be sure to check the javascript sdk documentation in the [DeveloperCenter](https://developer.usw2.pure.cloud/api/rest/client-libraries/javascript/). Usually everything important is mentioned there.
