### ISSUE TITLE
window.postMessage API

### ISSUE THREAD

**Issue by aiosifelisl1** [MyPureCloud/platform-client-sdk-javascript#6]
Hi all. 
![image](https://user-images.githubusercontent.com/62757413/100905685-5920e980-3496-11eb-9e47-dd3446a27fe5.png)

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

In the above example I try to use the native postMessage API to send information from the within an iframe to the parent document. I see that I'm receiving a completely different payload/message than the one that is being posted. (`helperFunction:postIFrameMessage` is the sender and `Flights:onPostMessage` is the receiver)

Our website uses the Genesys JS sdk. With a brief search in the sdk I see that it somehow overrides the window.postMessage message.

![image](https://user-images.githubusercontent.com/62757413/100906076-c46abb80-3496-11eb-9037-cec717e42d78.png)

The code in the above screenshot is from the sdk. Is this a correct assumption? If the sdk overrides the native window.postMessage method, how is it possible to use it for other implementations along side with the sdk?

Thanks in advance.

**Comment by timsmithgenesys** [comment]
I can't find that code anywhere in this project. This repo is the source for the Platform API Client SDK. Maybe you're looking at a different library? Regardless, please make a post with further information about where you've found this on the Genesys Cloud Developer Forum. https://developer.mypurecloud.com/forum/
